trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    npm install
  displayName: 'Install dependencies'
- script: 
    npm run build --if-present
  displayName: 'Build'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
