export enum TripStatus {
  CANCELED = 'CANCELED',
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  FINISHED = 'FINISHED',
  PENDING_VALORATION = 'PENDING_VALORATION',
  READY_FOR_START = 'READY_FOR_START',
}
